export const SET_CONNECTED = 'set-connected'
export const SET_INITIALIZED = 'set-initialized'
export const SET_LOADING = 'set-loading'
export const SET_NAVIGATION = 'set-navigation'
export const SET_SCENES = 'set-scenes'
export const SET_TOASTS = 'set-toasts'
