export const SET_COLORS = 'set-colors'
export const SET_CONNECTED = 'set-connected'
export const SET_INITIALIZED = 'set-initialized'
export const SET_LOADING = 'set-loading'
export const SET_SCROLL = 'set-scroll'
export const SET_TOASTS = 'set-toasts'
